### ISSUE TITLE
Error when starting the container

### ISSUE THREAD

**Issue by Albertowue** [thkukuk/fritzbox-monitoring#5]
Hi, in the latest versions I encounter a problem when starting the container:
`"Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/entrypoint.sh": stat /entrypoint.sh: no such file or directory: unknown"`

I use the latest tag version, but if I use the tag version [1.0-7.1018] (or earlier) the container starts correctly.

This is my docker-compose.yml:

```
services:
  mrtg:
    container_name: mrtg
    image: thkukuk/fritzbox-bandwidth-monitor:latest
    volumes:
      - mrtg:/srv/www/htdocs
    ports:
      - 81:80
    environment:
      - TZ=Europe/Rome
      - FRITZBOX=x.x.x.x
      - PUID=1000
      - PGID=1000
    restart: unless-stopped
volumes:
  mrtg:
    external: true
```

I just tried it on a newly installed test VM and the problem is the same. Has anything been changed in the latest versions?
